db_host: database
db_name: georchestra
db_user: plui-evolution
db_password: plui-evolution
db_port: 5432

server_expose_port: 8082

admin_password: 4dM1nApp!

smtp_host: mailhog
smtp_port: 1025
smtp_username:
smtp_password:

ldap_host: ldap
ldap_port: 389
ldap_username: cn=admin,dc=georchestra,dc=org
ldap_password: secret

backend_url: https://tr.georchestra.open-groupe.com/plui-evolution/
